@startuml

title __BALLASTING's Class Diagram__\n

  namespace  {
    namespace ain {
      namespace ballasting {
        class main.ballasting.SeqData {
            - Streamer : int
            - Unit : int
            - seq10_mean : double
            - seq1_mean : double
            - seq2_mean : double
            - seq3_mean : double
            - seq4_mean : double
            - seq5_mean : double
            - seq6_mean : double
            - seq7_mean : double
            - seq8_mean : double
            - seq9_mean : double
            + SeqData()
            + getSeq10_mean()
            + getSeq1_mean()
            + getSeq2_mean()
            + getSeq3_mean()
            + getSeq4_mean()
            + getSeq5_mean()
            + getSeq6_mean()
            + getSeq7_mean()
            + getSeq8_mean()
            + getSeq9_mean()
            + getStreamer()
            + getUnit()
            + setSeq10_mean()
            + setSeq1_mean()
            + setSeq2_mean()
            + setSeq3_mean()
            + setSeq4_mean()
            + setSeq5_mean()
            + setSeq6_mean()
            + setSeq7_mean()
            + setSeq8_mean()
            + setSeq9_mean()
            + setStreamer()
            + setUnit()
            + toString()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace ballasting {
        class main.ballasting.ballasting_Controller {
            + BallTable : TreeTableView<SeqData>
            + BallastingLC : LineChart<Number, Number>
            + avgsButton : ToggleButton
            + ballColumnSeq1 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq10 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq2 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq3 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq4 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq5 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq6 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq7 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq8 : TreeTableColumn<SeqData, Number>
            + ballColumnSeq9 : TreeTableColumn<SeqData, Number>
            {static} + compass : List<Integer>
            + errorsButton : ToggleButton
            {static} + last_seq_data : List<Ballasting>
            + maxButton : ToggleButton
            + maxWA : Spinner<Double>
            + minButton : ToggleButton
            + minWA : Spinner<Double>
            {static} + seq : List<Integer>
            + skipHead : Spinner<Integer>
            + skipTail : Spinner<Integer>
            {static} + strList : List<Integer>
            {static} + tenSeq : List<SeqData>
            {static} + tenSeqMax : List<SeqData>
            {static} + tenSeqMin : List<SeqData>
            + xAxis : NumberAxis
            + yAxis : NumberAxis
            {static} ~ logger : Logger
            {static} - root : TreeItem<SeqData>
            {static} - str : int
            {static} + doBallasting()
            + drawChGraph()
            + fillTable()
            + initialize()
            + update()
            + updateData()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace ballasting {
        class main.ballasting.ballasting_Controller.Sortbystr {
            + compare()
        }
      }
    }
  }
  

  main.ballasting.ballasting_Controller +-down- main.ballasting.ballasting_Controller.Sortbystr
  main.ballasting.ballasting_Controller.Sortbystr .up.|> java.util.Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
