@startuml

title __GENERAL's Class Diagram__\n

  namespace  {
    namespace ain {
      namespace general {
        class main.general.PropertiesWorker {
            {static} + CONN_STRING : String
            {static} + CurrentPROJECT : String
            {static} + MySQLDB_IP : String
            {static} + PASSWORD : String
            {static} + USERNAME : String
            {static} + VESSEL : String
            {static} ~ logger : Logger
            {static} - prop : Properties
            {static} + ReadPreferences()
            {static} + saveImportPath()
            {static} + storeDBPreferences()
            {static} + storeProjectPreferences()
            {static} + storeVesselPreferences()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace general {
        class main.general.ReadData {
            {static} ~ logger : Logger
            {static} + getAllBatt()
            {static} + getBallastingDataForGraph()
            {static} + getCapGraphData()
            {static} + getChGraphData()
            {static} + getCompassList()
            {static} + getCutGraphData()
            {static} + getDataList()
            {static} + getErrBatt()
            {static} + getInsTestDates()
            {static} + getInsTestLimits()
            {static} + getInsTestRes()
            {static} + getLastSeq()
            {static} + getLeakageGraphData()
            {static} + getNoiseGraphData()
            {static} + getStrList()
            {static} + readBattDataForGraph()
            {static} + readBattDate()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace general {
        class main.general.ReadData.Sortbystr {
            + compare()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace general {
        class main.general.StoreData {
            {static} ~ logger : Logger
            {static} + storeProject()
        }
      }
    }
  }
  

  main.general.ReadData +-down- main.general.ReadData.Sortbystr
  main.general.ReadData.Sortbystr .up.|> java.util.Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
