@startuml

title __INSTEST's Class Diagram__\n

  namespace  {
    namespace ain {
      namespace insTest {
        class main.insTest.insTest_Controller {
            + CapButton : ToggleButton
            + CapColumn : TreeTableColumn<InsTestRes, Number>
            + CapHistogram : BarChart<String, Number>
            + CutButton : ToggleButton
            + CutoffColumn : TreeTableColumn<InsTestRes, Number>
            + CutoffHistogram : BarChart<String, Number>
            + InsTable : TreeTableView<InsTestRes>
            + InsTestDateDatePicker : DatePicker
            + LeakageButton : ToggleButton
            + LeakageColumn : TreeTableColumn<InsTestRes, Number>
            + LimitsTable : TableView<InsTestLimits>
            + NoiseButton : ToggleButton
            + NoiseColumn : TreeTableColumn<InsTestRes, Number>
            + SpreadLC : LineChart<String, Number>
            + StrSP : Spinner<Integer>
            + calcInfoArea : TextArea
            + capTolTF : TextField
            + cutTolTF : TextField
            + dS2 : Spinner<Integer>
            + dS3 : Spinner<Integer>
            + dS4 : Spinner<Integer>
            + dS5 : Spinner<Integer>
            + dS6 : Spinner<Integer>
            + errorsButton : ToggleButton
            + lkgTF : TextField
            + noiseTF : TextField
            + resultsTable : TableView<resultTable>
            + tS2 : Spinner<Integer>
            + tS3 : Spinner<Integer>
            + tS4 : Spinner<Integer>
            + tS5 : Spinner<Integer>
            + tS6 : Spinner<Integer>
            + xAxisIns : CategoryAxis
            + yAxisIns : NumberAxis
            ~ CalculatedLimits : List<InsTestLimits>
            ~ DecFormatOneOne : DecimalFormat
            {static} ~ logger : Logger
            - InsTestDates : List<LocalDate>
            - root : TreeItem<InsTestRes>
            - str : int
            + ShowCap()
            + ShowCut()
            + ShowLeakage()
            + ShowNoise()
            + drawChGraph()
            + fillTable()
            + getStats()
            + initialize()
            - limitsFunc()
            - update()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace insTest {
        class main.insTest.insTest_Controller.Sortbystr {
            + compare()
        }
      }
    }
  }
  

  namespace  {
    namespace ain {
      namespace insTest {
        class main.insTest.resultTable {
            + cap : int
            + cutoff : int
            + leakage : int
            + noise : int
            + streamer : int
            + total : int
            + getCap()
            + getCutoff()
            + getLeakage()
            + getNoise()
            + getStreamer()
            + getTotal()
            + resultTable()
            + setCap()
            + setCutoff()
            + setLeakage()
            + setNoise()
            + setStreamer()
            + setTotal()
        }
      }
    }
  }
  

  main.insTest.insTest_Controller +-down- main.insTest.insTest_Controller.Sortbystr
  main.insTest.insTest_Controller.Sortbystr .up.|> java.util.Comparator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
